### ISSUE TITLE
Deployment problem

### ISSUE THREAD

**Issue by jmlp1** [rancher/quickstart#100]
Followed Rancher Azure Quick Start Guide instructions, overcame few issues and typos in [RKE Terraform Provider Installation Instructions](https://github.com/rancher/terraform-provider-rke#using-the-provider)

The deployment started and the Quickstart-Rancher-Quickstart Azure RG was created successfully and resources were starting to be deployed in my chosen location

![image](https://user-images.githubusercontent.com/67766356/86418732-0796e780-bcc9-11ea-9aa0-28549c99df6f.png)

However, I got stuck in this step: "module.rancher_common.rancher2_bootstrap.admin: Creating..."

I am not very proficient with Rancher and coding, any given help will be very much appreciated

![image](https://user-images.githubusercontent.com/67766356/86418876-80963f00-bcc9-11ea-9640-d3499b7414e3.png)

**Comment by nikkelma** [comment]
It looks like the Helm release for the Rancher server failed - have you tried running `terraform apply` again? Could have been a one-off issue ... if that doesn't fix it, we'd need to dive deep into what exactly went wrong using the `helm` and `kubectl` CLIs.

**Comment by jmlp1** [comment]
Suddenly the issue sorted itself, no changes done, just launched terraform apply again

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nikkelma** [comment]
Great to hear!
