### ISSUE TITLE
Kubelet uses wrong internal IP in Vagrant cluster

### ISSUE THREAD

**Issue by c0deaddict** [rancher/quickstart#102]
When provisioning a multi-node cluster on Vagrant, everything looks fine at first sight. Cluster is all green and I can use `kubectl` to put some workloads on the cluster. However as soon as I try to `kubectl exec` or `kubectl logs` I get this error: https://github.com/kubernetes/kubernetes/issues/60835 

It appears the `kubelet` is using the address of interface `eth0` as it's internal address. This interface *always* has the address `10.0.2.15` for each node and is used by Vagrant for NAT. A solution would be to add an argument `--node-ip=172...` to the kubelet args, but I can't find no way to override this. Even changing the `Args` in the kubelet's `config.v2.json` and then rebooting the machine doesn't work as the cattle agent detects this change, and reverts back the arguments....

Is there any other way to fix this?

**Comment by chrisurwin** [comment]
I've added an update to the rancher node script to add the node IP and hostname into /etc/hosts, 
`kubectl get nodes -o wide` now also now shows the correct IP. 

I'll leave this issue open for a couple of days so please test and confirm it has solved your issue.

**Comment by c0deaddict** [comment]
Thanks for the fix! I can confirm that it works now.
