### ISSUE TITLE
vagrant quickstart - sed: /etc/fstab: No such file or directory

### ISSUE THREAD

**Issue by oxr463** [rancher/quickstart#125]
```
==> node-01: Cloning VM...
==> node-01: Matching MAC address for NAT networking...
==> node-01: Checking if box 'chrisurwin/RancherOS' version '1.5.1' is up to date...
==> node-01: Setting the name of the VM: node-01
==> node-01: Fixed port collision for 22 => 2222. Now on port 2205.
==> node-01: Clearing any previously set network interfaces...
==> node-01: Preparing network interfaces based on configuration...
    node-01: Adapter 1: nat
    node-01: Adapter 2: hostonly
==> node-01: Forwarding ports...
    node-01: 22 (guest) => 2205 (host) (adapter 1)
==> node-01: Running 'pre-boot' VM customizations...
==> node-01: Booting VM...
==> node-01: Waiting for machine to boot. This may take a few minutes...
    node-01: SSH address: 127.0.0.1:2205
    node-01: SSH username: rancher
    node-01: SSH auth method: private key
    node-01: 
    node-01: Vagrant insecure key detected. Vagrant will automatically replace
    node-01: this with a newly generated keypair for better security.
    node-01: 
    node-01: Inserting generated public key within guest...
    node-01: Removing insecure key from the guest if it's present...
    node-01: Key inserted! Disconnecting and reconnecting using new SSH key...
==> node-01: Machine booted and ready!
[node-01] No Virtualbox Guest Additions installation found.
Updating GuestAdditions skipped.
==> node-01: Setting hostname...
==> node-01: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sed -i '/#VAGRANT-BEGIN/,/#VAGRANT-END/d' /etc/fstab

Stdout from the command:



Stderr from the command:

sed: /etc/fstab: No such file or directory
```

**Comment by DemonAzteck** [comment]
i have de same problem!

**Comment by 1Shiroyuuki1** [comment]
Same problem on Mac OS

vagrant version output:

`Installed Version: 2.2.10
Latest Version: 2.2.10`

**Comment by eduard-kistner** [comment]
Verfified on another Mac with other vagrant boxes running fine.

For me the main question is which script is calling this sed command ?

**Comment by oxr463** [comment]
> Verfified on another Mac with other vagrant boxes running fine.
> 
> For me the main question is which script is calling this sed command ?

None of the scripts in the repository explicitly invoke `sed`.
I think it is done in vagrant as part of the networking setup.

RancherOS does not come with an `/etc/fstab` file, hence the failure.

**Comment by 1Shiroyuuki1** [comment]
> None of the scripts in the repository explicitly invoke `sed`.
> I think it is done in vagrant as part of the networking setup.
> 
> RancherOS does not come with an `/etc/fstab` file, hence the failure.

Some 'sed' invoke here:
https://github.com/rancher/quickstart/blob/0f2b728d1288fda80c2cf92ce74ed9560fda26a3/vagrant/vagrant_rancheros_guest_plugin.rb#L58

As you thought. It is part of the networking setup.

**Comment by linusaranha** [comment]
Running into the same issue - Any workarounds?

**Comment by 1Shiroyuuki1** [comment]
After the Error I've done an another `vagrant up` command now it runs smoothly for some Reason.

**Comment by clintcolding** [comment]
This is an [issue](https://github.com/flatcar-linux/Flatcar/issues/182) with Vagrant 2.2.10. I was able to successfully run the vagrantfile after downgrading to [2.2.9](https://releases.hashicorp.com/vagrant/2.2.9/).

**Comment by 1Shiroyuuki1** [comment]
> This is an [issue](https://github.com/flatcar-linux/Flatcar/issues/182) with Vagrant 2.2.10. I was able to successfully run the vagrantfile after downgrading to [2.2.9](https://releases.hashicorp.com/vagrant/2.2.9/).

Other Vagrant boxes under v.2.2.10 are running fine so im not sure for if this is directly connected to your issue

**Comment by clintcolding** [comment]
> > This is an [issue](https://github.com/flatcar-linux/Flatcar/issues/182) with Vagrant 2.2.10. I was able to successfully run the vagrantfile after downgrading to [2.2.9](https://releases.hashicorp.com/vagrant/2.2.9/).
> 
> Other Vagrant boxes under v.2.2.10 are running fine so im not sure for if this is directly connected to your issue

Are your other Vagrant boxes missing the /etc/fstab file?

**Comment by 1Shiroyuuki1** [comment]
> > > This is an [issue](https://github.com/flatcar-linux/Flatcar/issues/182) with Vagrant 2.2.10. I was able to successfully run the vagrantfile after downgrading to [2.2.9](https://releases.hashicorp.com/vagrant/2.2.9/).
> > 
> > 
> > Other Vagrant boxes under v.2.2.10 are running fine so im not sure for if this is directly connected to your issue
> 
> Are your other Vagrant boxes missing the /etc/fstab file?

No. But i`ve found out the reason as well. Our Vagrant boxes runs under a customize image which is why the file exists.
So in a nutshell: You´re right

**Comment by cortopy** [comment]
I've just been trying [rancherd](https://rancher.com/blog/2020/rancherd-simplifies-rancher-deployment) as a way to do a quickstart for the latest rancher. I've been using it for a day and it's extremely good. I think it's a much better alternative to the vagrant tutorial

**Comment by oxr463** [comment]
> I've just been trying [rancherd](https://rancher.com/blog/2020/rancherd-simplifies-rancher-deployment) as a way to do a quickstart for the latest rancher. I've been using it for a day and it's extremely good. I think it's a much better alternative to the vagrant tutorial

Glad to hear it, although definitely off-topic for this issue.

**Comment by nikkelma** [comment]
> This is an [issue](https://github.com/flatcar-linux/Flatcar/issues/182) with Vagrant 2.2.10. I was able to successfully run the vagrantfile after downgrading to [2.2.9](https://releases.hashicorp.com/vagrant/2.2.9/).

@oxr463 Did this fix the issue for you? I know we're discussing a big refactor for the Vagrant quickstart to move away from RancherOS, that could be a possible solution for this issue as well.

**Comment by oxr463** [comment]
> > This is an [issue](https://github.com/flatcar-linux/Flatcar/issues/182) with Vagrant 2.2.10. I was able to successfully run the vagrantfile after downgrading to [2.2.9](https://releases.hashicorp.com/vagrant/2.2.9/).
> 
> @oxr463 Did this fix the issue for you? I know we're discussing a big refactor for the Vagrant quickstart to move away from RancherOS, that could be a possible solution for this issue as well.

I have not had the chance to try this yet. I still think migrating to CentOS 7 or another host OS would be the best solution in the long term.

**Comment by gerdemann** [comment]
I think the bug was solved with vagrant version 2.2.11

**Comment by angelosanramon** [comment]
fixed on 2.2.14

**Comment by jenting** [comment]
I'm facing the issue at vagrant version `2.2.10`. After upgrading vagrant to version `2.2.14`, it works well on openSUSE Leap 15.2.

**Comment by ToniIltanen** [comment]
i confirm the solution by @jenting, worked after upgrading vagrant
