### ISSUE TITLE
AWS - VPCIdNotSpecified: No default VPC for this user

### ISSUE THREAD

**Issue by claudioser** [rancher/quickstart#126]
trying to follow instructions, and getting :

Error: Error creating Security Group: VPCIdNotSpecified: No default VPC for this user
        status code: 400, request id: 00f9703c-2d2d-47b8-ad28-1907d95eeef6
  on infra.tf line 26, in resource "aws_security_group" "rancher_sg_allowall":
  26: resource "aws_security_group" "rancher_sg_allowall" {

credentials are fine ( even recreated new access keys), and tried adding ( or leaving empty)  region, prefix, instance_type.
default vpc's exist on all regions

**Comment by malfuncion** [comment]
After some deep searching, I found a post that told me I am encoI was able to push past this issue by recreating a default VPC from my Admin Console --> VPC --> Actions --> Create Default VPC. Hope this helps you!

**Comment by nikkelma** [comment]
Appreciate the insight, my gut feeling was this was some edge case with an EC2-Classic account. Curious if a re-create of the default VPC is a reliable fix, may not be easy in a larger account though.

**Comment by Emc1992** [comment]
I got passed this (then hit other issues) when I created a vpc and did a vpc_id = vpc.bla.id for the security groups however I ran outta time trying to hack through issue so didnt get this cleaned up

**Comment by demon** [comment]
Yes, recreating a default VPC will work around the issue. But I'd like to approach this from a different angle: it should be possible to deploy this to a VPC _other than_ your default VPC in a region. Many (most?) folks don't want to deploy to their default VPC.

**Comment by JohnWright-GSE** [comment]
Just tried deploying on AWS with no default VPC and hit this same error:

` Error: Error creating Security Group: VPCIdNotSpecified: No default VPC for this user`
 
 I see someone has got around this by hardcoding things, but I didn't see an example of what that would look like.  Any tips?

**Comment by muralidigi** [comment]
Even with the all ready created vpc, it still fails, When it launches the EC2 instance:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/38922863/185718275-926e6e9f-8360-476e-8f3d-537a1a048174.png">

I think this was written using EC2 Classic which is no longer supported:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-classic-platform.html

**Comment by njoylif** [comment]
ran into this as well...we are larger env. to point of: @nikkelma 
This example creates a security group named "MySecurityGroup" for the
specified VPC.

Command:

   aws ec2 create-security-group --group-name MySecurityGroup --description "My security group" --vpc-id vpc-1a2b3c4d

Output:

   {
       "GroupId": "sg-903004f8"
   }

For more information, see Using Security Groups in the *AWS Command
Line Interface User Guide*.

This worked successfully for me.
