### ISSUE TITLE
Fail to download cert-manager in azure deployment

### ISSUE THREAD

**Issue by pepesan** [rancher/quickstart#127]
I've tried to deploy a rancher instance into azure cloud using the documentation in:
https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/microsoft-azure-qs/

All variables configured related to the azure account, but I found an error during the installation:
Error: failed to download "https://charts.jetstack.io/charts/cert-manager-v0.15.1.tgz" (hint: running `helm repo update` may help)

  on ../rancher-common/helm.tf line 4, in resource "helm_release" "cert_manager":
   4: resource "helm_release" "cert_manager" {

I've tried to access from my computer to that url and works fine, seams a network error.

**Comment by nikkelma** [comment]
A usual resolution is to retry the `terraform apply` again, is this a consistent problem?

**Comment by pepesan** [comment]
I've tryied to aplly the terraform script multiple times :(

**Comment by nikkelma** [comment]
Interesting, ran the script in my own Azure subscription multiple times and encountered no such errors... are there any global limitations on the account/subscription/environment that would prevent the successful download from the jetstack chart repo?

**Comment by nikkelma** [comment]
This also happened after a failed AWS deployment according to the above linked issue, I'm unsure how exactly to recreate this ... the only guess I have is that some internal state in the Helm provider doesn't translate well across specific provider versions.
