### ISSUE TITLE
"terraform apply --auto-approve" command failed in GCP 

### ISSUE THREAD

**Issue by tonythian** [rancher/quickstart#133]
I followed the instructions on this link to setup rancher on my GCP account:
https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/google-gcp-qs/

Managed to install terraform & cloned the git report for this quickstart and no problem with command "terraform init", but the next command failed with error.  Rancher VM is created in my GCP but not running. :(

> mythreesixzero@c9-demo-backend-1:~/quickstart/gcp$ terraform apply --auto-approve
data.google_compute_image.ubuntu: Refreshing state... [id=projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20201014]
google_compute_address.rancher_server_address: Refreshing state... [id=projects/my-project-1513217315731/regions/asia-southeast1/addresses/rancher-server-ipv4-address]
tls_private_key.global_key: Refreshing state... [id=389566cf0331bb2272a30b5ac28186967bc550b9]
google_compute_firewall.rancher_fw_allowall: Refreshing state... [id=projects/my-project-1513217315731/global/firewalls/c9-rancher-allowall]
google_compute_address.quickstart_node_address: Refreshing state... [id=projects/my-project-1513217315731/regions/asia-southeast1/addresses/quickstart-node-ipv4-address]
local_file.ssh_private_key_pem: Refreshing state... [id=fe062bd869bdade492c314f1f798c8fe061cdea1]
local_file.ssh_public_key_openssh: Refreshing state... [id=a3bdc3129e9a98ca2c4e1fc4808a30d2b2f73997]
google_compute_instance.rancher_server: Refreshing state... [id=projects/my-project-1513217315731/zones/asia-southeast1-b/instances/c9-rancher-server]
module.rancher_common.rke_cluster.rancher_cluster: Refreshing state... [id=646b9d1c-e885-49ec-af7f-22a57a80def7]
google_compute_instance.rancher_server: Modifying... [id=projects/my-project-1513217315731/zones/asia-southeast1-b/instances/c9-rancher-server]
module.rancher_common.rke_cluster.rancher_cluster: Destroying... [id=646b9d1c-e885-49ec-af7f-22a57a80def7]
module.rancher_common.rke_cluster.rancher_cluster: Destruction complete after 0s
google_compute_instance.rancher_server: Still modifying... [id=projects/my-project-1513217315731/zones...utheast1-b/instances/c9-rancher-server, 10s elapsed]
google_compute_instance.rancher_server: Still modifying... [id=projects/my-project-1513217315731/zones...utheast1-b/instances/c9-rancher-server, 20s elapsed]
google_compute_instance.rancher_server: Modifications complete after 24s [id=projects/my-project-1513217315731/zones/asia-southeast1-b/instances/c9-rancher-server]
module.rancher_common.rke_cluster.rancher_cluster: Creating...

Error: 
============= RKE outputs ==============
time="2020-10-20T04:20:27Z" level=info msg="Deleting RKE cluster..."
time="2020-10-20T04:20:27Z" level=info msg="Tearing down Kubernetes cluster"
time="2020-10-20T04:20:27Z" level=info msg="[dialer] Setup tunnel for host [34.87.95.118]"
time="2020-10-20T04:20:28Z" level=warning msg="Failed to set up SSH tunneling for host [34.87.95.118]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access the service on /var/run/docker.sock. The service might be still starting up. Error: ssh: rejected: connect failed (open failed)"
time="2020-10-20T04:20:28Z" level=warning msg="Removing host [34.87.95.118] from node lists"
time="2020-10-20T04:20:51Z" level=info msg="[rke_provider] rke cluster changed arguments: map[cluster_name:true kubernetes_version:true nodes:true]"
time="2020-10-20T04:20:51Z" level=info msg="Creating RKE cluster..."
time="2020-10-20T04:20:51Z" level=info msg="Initiating Kubernetes cluster"
time="2020-10-20T04:20:52Z" level=info msg="[dialer] Setup tunnel for host [34.87.95.118]"
time="2020-10-20T04:20:52Z" level=warning msg="Failed to set up SSH tunneling for host [34.87.95.118]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access the service on /var/run/docker.sock. The service might be still starting up. Error: ssh: rejected: connect failed (open failed)"
time="2020-10-20T04:20:52Z" level=warning msg="Removing host [34.87.95.118] from node lists"
time="2020-10-20T04:20:52Z" level=warning msg="[state] can't fetch legacy cluster state from Kubernetes: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [34.87.95.118]"
time="2020-10-20T04:20:52Z" level=info msg="[certificates] Generating CA kubernetes certificates"
time="2020-10-20T04:20:52Z" level=info msg="[certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates"
time="2020-10-20T04:20:53Z" level=info msg="[certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates"
time="2020-10-20T04:20:53Z" level=info msg="[certificates] Generating Kubernetes API server certificates"
time="2020-10-20T04:20:53Z" level=info msg="[certificates] Generating Service account token key"
time="2020-10-20T04:20:53Z" level=info msg="[certificates] Generating Kube Controller certificates"
time="2020-10-20T04:20:53Z" level=info msg="[certificates] Generating Kube Scheduler certificates"
time="2020-10-20T04:20:53Z" level=info msg="[certificates] Generating Kube Proxy certificates"
time="2020-10-20T04:20:53Z" level=info msg="[certificates] Generating Node certificate"
time="2020-10-20T04:20:53Z" level=info msg="[certificates] Generating admin certificates and kubeconfig"
time="2020-10-20T04:20:54Z" level=info msg="[certificates] Generating Kubernetes API server proxy client certificates"
time="2020-10-20T04:20:54Z" level=info msg="Successfully Deployed state file at [/home/mythreesixzero/quickstart/gcp/terraform-provider-rke-tmp-324924731/cluster.rkestate]"
time="2020-10-20T04:20:54Z" level=info msg="Building Kubernetes cluster"

Failed running cluster err:Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config
========================================

  on ../rancher-common/rke.tf line 4, in resource "rke_cluster" "rancher_cluster":
   4: resource "rke_cluster" "rancher_cluster" {

**Comment by nikkelma** [comment]
It appears you had some existing infrastructure in GCP that RKE is trying to modify in place ... have you tried destroying the setup, then re-running the apply command?
