### ISSUE TITLE
Vagrant quickstart runs out of memory & the API server fails

### ISSUE THREAD

**Issue by stefanlasiewski** [rancher/quickstart#14]
I'm following the Rancher Quickstart guides at https://github.com/rancher/quickstart & https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-vagrant/ . Following those instructions does not result in a working Rancher cluster.

It appears that the API starts but becomes unresponsive. Please see the screenshot.

Steps to reproduce:

1. Clone the repo:

```
$ git clone https://github.com/rancher/quickstart ~/Vagrant/rancher-2.0/
Cloning into '/Users/stefanl/Vagrant/rancher-2.0'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 98 (delta 4), reused 13 (delta 2), pack-reused 72
Unpacking objects: 100% (98/98), done.
```

2. Start the cluster without any modifications:

```
$ cd ~/Vagrant/rancher-2.0/vagrant/
$ vagrant up
Config: {"default_password"=>"admin", "version"=>"latest", "kubernetes_version"=>"v1.11.2-rancher1-1", "ROS_version"=>"1.4.0", "server"=>{"cpus"=>1, "memory"=>1500}, "node"=>{"count"=>1, "cpus"=>1, "memory"=>1500}, "ip"=>{"master"=>"172.22.101.100", "server"=>"172.22.101.101", "node"=>"172.22.101.111"}, "linked_clones"=>true, "net"=>{"private_nic_type"=>"82545EM", "network_type"=>"private_network"}}

Bringing machine 'server-01' up with 'virtualbox' provider...
Bringing machine 'node-01' up with 'virtualbox' provider...
......
    node-01: Status: Downloaded newer image for rancher/rancher-agent:v2.1.0
    node-01: c819502471345d044db3a3ba482a9a53ce8b9e5729c664151a7d83d3d3825e35
$
```

3. Log into the server at https://172.22.101.101/login, which redirects us to https://172.22.101.101/g/clusters.

4. Wait about 10 minutes.

5. Notice the cluster named 'quickstart' is in the State of 'Unavailable' and reports the following error, even after 10 minutes:

`Failed to communicate with API server: Get https://172.22.101.111:6443/api/v1/componentstatuses?timeout=30s: waiting for cluster agent to connect
`

See the following screenshot:

![image](https://user-images.githubusercontent.com/142752/46834570-9bd85280-cd60-11e8-88f8-ebfee9ecaa00.png)

System details:
* Mac Version: 10.13.6 (High Sierra)
* Vagrant version: Vagrant 2.1.2
* Virtualbox version: 5.2.18
* Rancher v2.1.0

**Comment by stefanlasiewski** [comment]
I've tried this a couple times, and sometimes the 'quickstart' cluster is actually green, but 5 minutes later it became unavailable again.

**Comment by stefanlasiewski** [comment]
I logged into the VM, and could not get a response from the API server from inside the VM:

```
$ vagrant ssh node-01
[rancher@node-01 ~]$ wget "https://172.22.101.111:6443/api/v1/componentstatuses?timeout=30s"
Connecting to 172.22.101.111:6443 (172.22.101.111:6443)
(Never responds)
```

And something appears to be spinning out of control:

```
[rancher@node-01 ~]$ uptime
 21:55:42 up 26 min,  load average: 17.28, 16.58, 13.43
```

**Comment by chrisurwin** [comment]
in the config.yaml can you bump up the memory for the node and the server from 1500 to 2500 and see if that solves the problem. This is likely a resource issue. I can't replicate the problem you have but changing these should hopefully solve the problem for you.

**Comment by stefanlasiewski** [comment]
Yes indeed, bumping up the memory to 2000 or more seems to work. For whatever reason, it seems that etcd on my setup consumes alot of RAM & 1.5GB is not enough.

Unfortunately, I get a similar behavior if I add more then a couple workloads to the cluster. The system eventually runs out of memory. I understand this is a simple 'quickstart' system with a single worker node, but it would be great emulating a customer workload wouldn't kill the administrative functionality.

I'm checking out your Vagrant project, since that's intended to be more robust.
