### ISSUE TITLE
Quickstart examples AWS, DO and Vagrant not working

### ISSUE THREAD

**Issue by ollin** [rancher/quickstart#151]
Hello, 

I tried your AWS and Digitalocean examples with the head from master.
- both have timeouts
- example aws:
  - `aws_instance.rancher_server (remote-exec): Connecting to remote host via SSH... `
     ...

I tried the vagrant example
- no access via https://172.22.101.101 to the console

Something broken in the quickstart examples?

**Comment by bashofmann** [comment]
I just tried both the aws and do examples and they work fine. From the limited information provided, it looks like terraform is unable to ssh into the aws instance it just created.
The reason of this could be either something preventing the ssh connection to the remote server on the machine where you are running terraform on (local and network firewalls, corporate proxies, ssh settings). Or it could be that the default vpc, where the terraform module create the ec2 instances, is somehow limited and does not accept ssh connections from where you are running terraform.

**Comment by ollin** [comment]
Thx for the answer. I tried it 3 times and then the ssh connection was fine. No idea what was going on. :|
