### ISSUE TITLE
Quickstart example DO not working

### ISSUE THREAD

**Issue by BoKKeR** [rancher/quickstart#154]
I have tried deploying 2 times, the steps finish successfully, the droplets are created. When trying to access the IP I get:

`default backend - 404`

When accessing the host I get an SSL error.

Could you verify that the config is still valid for DO? 

Also, does the server droplet have to be the same size as the worker node? Isn't that wasteful?

**Comment by bashofmann** [comment]
You have to use the hostname. The ingress controller inside the cluster routes incoming traffic to the Rancher pods via the hostname. If you just access it with the IP address, it does not know where to route to and returns a 404.

The SSL error/warning in the browser is expected, these quickstarts use self-signed certificates. You can just skip the error and trust the certificate. If you configure your own DNS names, instead of a xip.io one, you can also use Let'sEncrypt or provide your own certificates. See https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/#4-choose-your-ssl-configuration.

**Comment by Canuckaholic** [comment]
I'm trying the DO QuickStart and while running `terraform apply --auto-approve` it errors with:
```
Error: RKE version is not supported [v1.19.7-rancher1-1 v1.19.6-rancher1-1 v1.19.4-rancher1-1 v1.19.3-rancher1-1 v1.19.2-rancher1-1 v1.18.9-rancher1-1 v1.18.6-rancher1-2 v1.18.3-rancher2-1 v1.17.17-rancher1-1 v1.17.16-rancher1-1 v1.17.14-rancher1-1 v1.17.13-rancher1-2 v1.17.13-rancher1-1 v1.17.12-rancher1-1 v1.17.11-rancher1-1 v1.17.6-rancher2-2 v1.17.5-rancher1-1 v1.17.4-rancher1-2 v1.17.4-rancher1-1 v1.17.3-rancher1-1 v1.17.2-rancher1-2 v1.17.2-rancher1-1 v1.17.0-rancher1-2 v1.17.0-rancher1-1 v1.16.15-rancher1-4 v1.16.15-rancher1-2 v1.16.14-rancher1-1 v1.16.10-rancher2-2 v1.16.10-rancher2-1 v1.16.9-rancher1-1 v1.16.8-rancher1-1 v1.16.6-rancher1-1 v1.16.3-rancher1-1 v1.16.2-rancher2-1 v1.16.2-rancher1-1 v1.16.1-rancher1-1 v1.15.12-rancher2-7 v1.15.12-rancher2-5 v1.15.12-rancher2-4 v1.15.12-rancher2-2 v1.15.12-rancher1-1 v1.15.11-rancher1-3 v1.15.11-rancher1-1 v1.15.6-rancher1-2 v1.15.5-rancher1-2 v1.15.4-rancher1-2 v1.15.3-rancher1-1 v1.14.10-rancher1-1 v1.14.10-rancher1-0 v1.14.9-rancher1-2 v1.14.9-rancher1-1 v1.14.8-rancher1-1 v1.14.7-rancher1-1 v1.14.6-rancher1-1 v1.14.5-rancher1-1 v1.14.1-rancher1-2 v1.13.12-rancher2-1 v1.13.12-rancher1-1 v1.13.11-rancher1-1 v1.13.9-rancher1-1 v1.13.7-rancher1-1 v1.13.5-rancher1-2 v1.13.5-rancher1-1 v1.13.4-rancher1-2 v1.13.4-rancher1-1 v1.13.1-rancher1-2 v1.13.1-rancher1-1 v1.12.10-rancher1-2 v1.12.9-rancher1-1 v1.12.7-rancher1-4 v1.12.7-rancher1-3 v1.12.7-rancher1-2 v1.12.6-rancher1-1 v1.12.5-rancher1-2 v1.12.3-rancher1-1 v1.12.1-rancher1-1 v1.11.9-rancher1-2 v1.11.9-rancher1-1 v1.11.8-rancher1-1 v1.11.3-rancher1-1 v1.11.1-rancher1-1 v1.10.11-rancher1-1 v1.10.5-rancher1-2 v1.10.5-rancher1-1 v1.10.1-rancher2-1 v1.9.7-rancher2-2 v1.9.5-rancher1-1 v1.8.11-rancher2-1] got v1.18.12-rancher1-1

  on ../rancher-common/rancher.tf line 16, in resource "rancher2_cluster" "quickstart_workload":
  16: resource "rancher2_cluster" "quickstart_workload" {
```

**Comment by bashofmann** [comment]
@Canuckaholic Just tried it out and works fine for me. Did you modify `rke_kubernetes_version` or `workload_kubernetes_version` ?

**Comment by Canuckaholic** [comment]
Hello. So I figured it out. You will get this error if you try to create a droplet on DO that is anything less than 4GB. 

Adrian (AJ)
778-772-7787

**Comment by bashofmann** [comment]
Closing this issue. The default droplet size is `s-2vcpu-4gb`.
