### ISSUE TITLE
AWS Quickstart has an invalid Security group definition.

### ISSUE THREAD

**Issue by johnduhart** [rancher/quickstart#16]
https://github.com/rancher/quickstart/blob/3b4d1c6f2408de453bad100c94e92a57122b955d/aws/main.tf#L98-L114

* A protocol_id of `"-1"` is not valid for security groups in EC2-Classic.
* Egress are not valid for EC2-Classic security groups.

**Comment by johnduhart** [comment]
Okay, even after fixing the security group, the t3 instance type does not support EC2 Classic.

```
* aws_instance.rancherserver: Error launching source instance: VPCResourceNotSpecified: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
	status code: 400, request id: b6a4f090-16dc-4bda-b312-7b457c81e32b
```

**Comment by scottconrad88** [comment]
+1 been getting the same errors when using the quick start guides

**Comment by Oats87** [comment]
Currently, our Terraform AWS Quickstart is not compatible with EC2 Classic. We are working on bringing an additional Terraform quickstart folder for EC2 classic that should work out of the box to help resolve these issues.

**Comment by rossmckelvie** [comment]
It would be great if this security group wasn't wide open to the world by default.

**Comment by nikkelma** [comment]
Is there still a need for EC2 Classic support? [Docs around this platform](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-classic-platform.html) indicate that accounts created after December 4, 2013 don't support this option, can we close this issue out?
