### ISSUE TITLE
Unable to git clone

### ISSUE THREAD

**Issue by Rob-Clancy-Git-Hub** [rancher/quickstart#167]
IGNORE this its an error with my Mac upgraded my OS and now mac is causing the issyue

I am unable to git clone this QS, has stopped working and give the error below - error: invalid active developer path

robertclancy@192 aws-rancher-qs-3.5 % git clone https://github.com/rancher/quickstart.git
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
robertclancy@192 aws-rancher-qs-3.5 % 

Seems there are a few issue with the repo in the past few days ????

**Comment by bashofmann** [comment]
The repository can be cloned just fine. The error clearly indicates a problem with your local git cli: https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

**Comment by Rob-Clancy-Git-Hub** [comment]
Thanks, I realised after its an issue with my MAC, thanks for quick answer :-)
