### ISSUE TITLE
Error running vagrant up

### ISSUE THREAD

**Issue by ToniIltanen** [rancher/quickstart#170]
The following error is resulting, when running vagrant up

```==> server-01: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 95 of file VBoxManageHostonly.cpp
```

Host: MacOS 11.3.1

**Comment by ToniIltanen** [comment]
fixed by updating vagrant to latest version

**Comment by stefanlasiewski** [comment]
Posting here for posterity.

This happened to me today with VirtualBox 6.1.36 and Vagrant 2.3.0 (Released 2 weeks ago) and macOS Monterey.

You might have luck with the solution described at https://laracasts.com/discuss/channels/general-discussion/homestead-macos-monterey-boot-issue-headless-error-virtualbox?page=1&replyId=744904 . However for me, I simply had to reboot my Mac to get this to work again.
