### ISSUE TITLE
Rancher 2.6 deployment failure

### ISSUE THREAD

**Issue by ab-mohamed** [rancher/quickstart#182]
Hi, 

I have some questions regarding the Rancher GCP quickstart guide `https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/deployment/google-gcp-qs/`

1. When I use the default Terraform values in the `terraform.tfvars` file, the created Rancher server version is `2.5.7` (the default version according to `variables.tf `file). 
The deployment is failed when I update the `terraform.tfvars` file to use the most recent Rancher version `2.6.0`. 

Here are the `terrafrom.tfvars` configurations that create Rancher `2.5.7`:
```
$ grep -v "#" terraform.tfvars | awk NF
gcp_account_json = "sa-key.json"
gcp_project = "<PROJECT ID>"
rancher_server_admin_password = "<TEMP PASSWORD>"
```

And here is the updated configurations to create Rancher 2.6.0:
```
$ grep -v "#" terraform.tfvars | awk NF
gcp_account_json = "sa-key.json"
gcp_project = "<PROJECT ID>"
rancher_server_admin_password = "<TEMP PASSWORD>"
gcp_region = "us-west1"
gcp_zone = "us-west1-a"
machine_type = "n1-standard-2"
rancher_version = "2.6.0"
```

The error message was shown after executing `terraform apply --auto-approve` command  from the Google Cloud Shell is:
```
╷
│ Warning: Empty provider configuration blocks are not required
│
│   on ../rancher-common/provider.tf line 2:
│    2: provider "local" {
│
│ Remove the local provider block from module.rancher_common.
│
│ (and one more similar warning elsewhere)
╵
╷
│ Error: [ERROR] Login with admin user: Doing  user logging: error Unauthorized
│
│   with module.rancher_common.rancher2_bootstrap.admin,
│   on ../rancher-common/rancher.tf line 4, in resource "rancher2_bootstrap" "admin":
│    4: resource "rancher2_bootstrap" "admin" {
```

Notice that I cannot determine the best value for `docker_version`,  `rke_kubernetes_version`, and `workload_kubernetes_version` as there is no support matrix yet for Rancher `2.6.0` in the `https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.5.9/` support matrix guide. The latest version there is 2.5.9. 

2. Is there any plans to extend this project to create Rancher HA environment on GCP?

3. What is the current status of using SLES instead of Ubuntu?

**Comment by ab-mohamed** [comment]
@bashofmann Thank you for the quick update. Any estimated time to support Rancher 2.6.0? 

Some more questions: 
1. Do we have any current Rancher 2.5.x Terraform-based guide to implementing HA Rancher on GCP? or any other CSP? 
2. Is there any plan to use SLES instead of Ubuntu (the current used OS)? 

Thank you in advance. :)

**Comment by giuseppeCozzolino** [comment]
Any update about this?

**Comment by bashofmann** [comment]
WIP: https://github.com/bashofmann/quickstart/tree/rancher-2.6.0
