### ISSUE TITLE
Unable to deploy the quickstart on AWS

### ISSUE THREAD

**Issue by gsbagga** [rancher/quickstart#186]
I am unable to deploy the quickstart template to AWS. I tried with the latest Terraform version 1.0.8 but got error while creating the security group. I then tried with version 0.13 just to make sure but still getting these errors

1. First error is about security group ingress rule has a value of "-1" for protocol, it needs to be "tcp". 
2. After changing above it complains from egress group. Gives an error that security group not found
3. I commented the egress rule just for testing, but then EC2 creation errored out with "Error: Error launching source instance: VPCResourceNotSpecified: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request."

This template does not refer VPC at all. Am I doing something wrong? Have anyone deployed this successfully? What could I be missing.

**Comment by gsbagga** [comment]
I just checked and in the region I was using there is no default VPC. I will try it in another region and report back. Thank you so much bashofmann. These errors now make sense to me.

**Comment by bashofmann** [comment]
Ok, I'll close this issue then in favor of https://github.com/rancher/quickstart/issues/126. Adapting this module to use other, non-default VPCs is tracked there.
