### ISSUE TITLE
vagrant up fails on Mac OS 11.6.1, Virtualbox 6.1.28 r147628 (Qt5.6.3)

### ISSUE THREAD

**Issue by andreyyudin** [rancher/quickstart#187]
The error is:

> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["hostonlyif", "ipconfig", "vboxnet5", "--ip", "172.22.101.1", "--netmask", "255.255.255.0"]
> 
> Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
> VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

One possible solution might be outlined here https://discuss.hashicorp.com/t/vagrant-2-2-18-osx-11-6-cannot-create-private-network/30984/4

**Comment by NetPenguins** [comment]
As per the the discussion you linked changing the IP address range to 192.168.56.0/21 will correct the issue. If you haven't done so already make sure your VB and Vagrant are on the latest version (time of writing that is 6.1.28 and 2.2.19 respectively.) Then change the ip addresses to reflect the new range constraint swapping 172.22.101.101 for 192.168.56.101 for example. I can open a PR for this if its desired.

**Comment by bashofmann** [comment]
@NetPenguins If you have the time, that'd be great.

**Comment by NetPenguins** [comment]
@bashofmann done.

**Comment by bashofmann** [comment]
Fixed by https://github.com/rancher/quickstart/pull/191
