### ISSUE TITLE
AWS QuickStart (Terraform) is broken out of the box

### ISSUE THREAD

**Issue by armenr** [rancher/quickstart#188]
Following along with these materials from this Rancher documentation: 
https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/deployment/amazon-aws-qs/

After setting up AWS Credentials (and not changing anything else), I run a terraform plan + terraform apply...and this is what I get. 

`Error: RKE version is not supported...`

Steps to reproduce:

- Use any AWS account
- Follow tutorial steps
- `terraform apply --auto-approve`
- Deployment goes boom 💥

What's particularly painful about this is that Terraform doesn't manage to gracefully handle the error, and breaks during deploy.

As a result, the statefile is not dependable, and we are not able to destroy/remove the partial deployment and all of the resources it creates.

Now, I need to go through our AWS account to manually find and remove the resources that were orphaned during the deployment.

As a potential new customer (paying customer/hosted) who was trying to deploy Rancher for analysis and comparison, this is really turning us away from considering Rancher for our business and for our customers.

Please advise.

**Comment by bashofmann** [comment]
RKE version v1.20.11-rancher1-1 seems to have been pulled for some reason. Changing the workload_kubernetes_version to one of the available versions from the error message fixes this issue.

Fixed by https://github.com/rancher/quickstart/commit/1b609cebad4ecce458ad61171ae7657a7bdce536
