### ISSUE TITLE
No HA for RancherServer for AWS quickstart terraform template

### ISSUE THREAD

**Issue by itzkumaran** [rancher/quickstart#19]
Dear Team, 

We are trying to spin a production grade Rancher using the given AWS kickstart guide. But no HA for RancherServer for AWS quickstart terraform template as shown in the snippet below. But we do see that the RancherAgent supports HA configuration.

Does this template can be enhanced to support HA for Rancherserver?

```
resource "aws_instance" "rancherserver" {
  ami             = "${data.aws_ami.ubuntu.id}"
  instance_type   = "${var.type}"
  key_name        = "${var.ssh_key_name}"
  security_groups = ["${aws_security_group.rancher_sg_allowall.name}"]
  user_data       = "${data.template_cloudinit_config.rancherserver-cloudinit.rendered}"

  tags {
    Name = "${var.prefix}-rancherserver"
  }
}
```

**Comment by venkat123456789** [comment]
Hello Team, 
I am also looking for the same resource which i can leverage that and get the HA rancherserver up and running. 

That would be appreciated if we can walk me through how i can define something in the quickstart/AWS for to have a HA rancherserver 

Thanks
---

**Comment by ntkach** [comment]
It's not clear with this template (i'm using the aws) how this relates to the setup you get if you follow the general rancher 2.x installation docs.  The 2.x docs for example don't seem to have the equivalent of the "rancher-server" this quickstart setup creates (something that's "just" rancher servers as opposed to cluster running some workloads).

**Comment by alfonmga** [comment]
Yeah, I agree. A Terraform template to deploy quickly a production Rancher 2.x infrastructure would make us life easier.

**Comment by superseb** [comment]
Quickstart is aimed to quickly deploy Rancher in the simplest way possible. This is the single node install as it doesn't involve setting up a cluster to run Rancher on. The quickstart is meant to be as lean as possible, there won't be HA added to the quickstart. If any is released, it will be in the docs or in a separate repository under the `rancher` org.
