### ISSUE TITLE
[docs] Warning: Value for undeclared variable - The root module does not declare a variable named "ssh_key_file_name" but a value was found in file "terraform.tfvars"

### ISSUE THREAD

**Issue by ceefour** [rancher/quickstart#192]
When applying `hcloud`:

* https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/deployment/hetzner-cloud-qs/ mentions `ssh_key_file_name`
* https://github.com/rancher/quickstart/tree/master/rancher-common#ssh_private_key_pem mentions `ssh_private_key_pem`

Neither seems to be accurate:

```
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "ssh_private_key_pem" but a value was found in
│ file "terraform.tfvars". If you meant to use this value, add a "variable" block to the
│ configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide certain "global"
│ settings to all configurations in your organization. To reduce the verbosity of these warnings, use
│ the -compact-warnings option.
```

So, what is the correct variable?

**Comment by bashofmann** [comment]
The documentation is outdated. Since https://github.com/rancher/quickstart/pull/86 the SSH keys are auto generated. After the `terraform apply`, you'll have a `id_rsa` and `id_rsa.pub` file in the modules directory.
I'll update the documentation accordingly.

**Comment by bashofmann** [comment]
The documentation update has been merged.

**Comment by ceefour** [comment]
Thanks you @bashofmann
