### ISSUE TITLE
quickstart-aws-custom Cluster stuck in "Provisioning" State

### ISSUE THREAD

**Issue by ecda909** [rancher/quickstart#200]
Hi, today I tried to deploy the Rancher cluster based on the quickstart documentation found here: https://rancher.com/docs/rancher/v2.5/en/quick-start-guide/deployment/amazon-aws-qs/#destroying-the-environment I got the Rancher Sever node running fine and the single node cluster is provisioned as expected, however the quickstart-aws-custom cluster is stuck in the "Provisioning" state (this has been stuck for about an hour). The instance is provisioned though, it's just not showing in the Rancher Dashboard as being up. Is there anything I can do to 

<img width="994" alt="Screen Shot 2022-01-21 at 3 13 02 PM" src="https://user-images.githubusercontent.com/20650573/150593889-072b9be2-1f29-4eb3-95ec-b3965ed4ceb5.png">
either bring it up or deploy just the single-node cl

<img width="1049" alt="Screen Shot 2022-01-21 at 3 13 30 PM" src="https://user-images.githubusercontent.com/20650573/150593968-bc53eec5-0b49-4861-aec2-e9197c524ad6.png">
uster without the quickstart-aws-custom cluster?

Thanks, there are screenshots attached if needed.

**Comment by thinkmassive** [comment]
I hit the same issue. According to `cloud-init-output.log` the provisioning script exits when it tries to install docker, but docker is already installed (maybe recently added to the base AMI?) The service is disabled, so you need to start it with `sudo systemctl start docker`.

With the `docker` service running, you can proceed with the quickstart by running the command (`sudo docker run ...`) provided on the Registration tab of the page "Cluster:  quickstart-aws-custom"

**Comment by bashofmann** [comment]
Thanks for the debugging work @thinkmassive . Fixed with https://github.com/rancher/quickstart/commit/ca34446008a4fabd18e70f34d43f0497cc8693b1.
