### ISSUE TITLE
Error: could not download chart

### ISSUE THREAD

**Issue by tomreitsma** [rancher/quickstart#204]
While trying to create a rancher server on digital ocean, it fails on the cert-manager step:

```
module.rancher_common.helm_release.cert_manager: Creating...
╷
│ Error: could not download chart: failed to download "https://charts.jetstack.io/charts/cert-manager-v1.5.3.tgz" at version "v1.5.3"
│
│   with module.rancher_common.helm_release.cert_manager,
│   on ../rancher-common/helm.tf line 4, in resource "helm_release" "cert_manager":
│    4: resource "helm_release" "cert_manager" {
```

**Comment by bashofmann** [comment]
Are you using the current version or an older one? Currently the module is using cert-manager 1.7.1 (https://github.com/rancher/quickstart/blob/master/do/variables.tf#L47). Nonetheless, the download URL looks correct and works for me. I can also successfully create clusters at DigitalOcean.

The helm chart is downloaded locally where you run Terraform. Are you maybe using some firewall, proxy configuration or virus/malware scanner that blocks the download?

Can you extend the Terraform log level (`TF_LOG=debug terraform apply`), this should hopefully give some more details on why the download fails.

**Comment by yoonhoGo** [comment]
Hi. I have the same problem with AWS QuickStart template.

```
Changes to Outputs:
  + workload_node_ip = (known after apply)
module.rancher_common.helm_release.cert_manager: Creating...
╷
│ Error: could not download chart: failed to download "https://charts.jetstack.io/charts/cert-manager-v1.7.1.tgz" at version "v1.7.1"
│
│   with module.rancher_common.helm_release.cert_manager,
│   on ../rancher-common/helm.tf line 4, in resource "helm_release" "cert_manager":
│    4: resource "helm_release" "cert_manager" {
│
╵
```

If I click the link, I can download the chart file. I guess 'terraform.tfvars' file is no problom.
When I try above comment, I don't know what should say some logs.

**Comment by yoonhoGo** [comment]
I resolve this error temporary way.

```shell
$cd quickstart/aws
$curl -O https://charts.jetstack.io/charts/cert-manager-v1.7.1.tgz
$tar -xvzf cert-manager-v1.7.1.tgz
$curl -O https://releases.rancher.com/server-charts/latest/rancher-2.6.4.tgz
$tar -xvzf rancher-2.6.4.tgz
```

If someone finds a basic solution, please fix it.

**Comment by bashofmann** [comment]
Maybe, you are still running into this one: https://github.com/hashicorp/terraform-provider-helm/issues/630. Do you already have the jetstack helm repository in you local helm repository index (`helm repo list`)? If yes, could you try to do a `helm repo update` and then try running `terraform apply` again?

**Comment by biandopa** [comment]
I had the same problem and the `helm repo update` command didn't work, but removing it from the helm repo with `helm repo remove jetstack` did

**Comment by krishnadce** [comment]
I've also faced the same issue with bitnami/redis chart. 

```
│ Error: could not download chart: chart "redis" version "12.5.1" not found in https://charts.bitnami.com/bitnami repository
│
│   with helm_release.redis,
│   on redis.tf line 219, in resource "helm_release" "redis":
│  219: resource "helm_release" "redis" {

```

I was able to resolve this by checking the available versions and using one of the available versions. The cause of the issue is that the version 12.5.1 is not found from the list.

To get the list of available versions, please run. 
```
helm search repo bitnami/redis --versions

NAME                    CHART VERSION   APP VERSION     DESCRIPTION
bitnami/redis           17.0.3          7.0.4           Redis(R) is an open source, advanced key-value ...
bitnami/redis           17.0.2          7.0.4           Redis(R) is an open source, advanced key-value ...
bitnami/redis           17.0.1          7.0.3           Redis(R) is an open source, advanced key-value ...
bitnami/redis           16.13.2         6.2.7           Redis(R) is an open source, advanced key-value ...
bitnami/redis           16.13.1         6.2.7           Redis(R) is an open source, advanced key-value ...
```
