### ISSUE TITLE
rke2 quickstart needed for aws terraform

### ISSUE THREAD

**Issue by unnimona** [rancher/quickstart#212]
i am looking for quickstart for aws terraform -- rke2

please provide it

**Comment by bashofmann** [comment]
The NeuVector aws quickstart includes an example how to set up a RKE2 cluster on AWS: https://github.com/rancher/quickstart/blob/master/neuvector/aws/rke2.tf.

**Comment by unnimona** [comment]
i tried the script. 
i was able to access neuvector dashboard
i did not find rke2 dashboard, nor ssh keys was generated
what to do?
