### ISSUE TITLE
Rancher server IP

### ISSUE THREAD

**Issue by crackcomm** [rancher/quickstart#22]
There is a different IP http://169.254.169.254/ and wrong API path, I don't know correct one so no PR.

https://github.com/rancher/quickstart/blob/master/aws/files/userdata_server#L53

**Comment by crackcomm** [comment]
Actually the path is wrong in DigitalOcean not sure about AWS one.

**Comment by superseb** [comment]
Not sure what exactly is wrong here, both AWS and DO are tested and working. What does the endpoint return for you and how to reproduce?

**Comment by crackcomm** [comment]
@superseb well maybe it was fixed it last commit.
