### ISSUE TITLE
aws permission error

### ISSUE THREAD

**Issue by julianfrank** [rancher/quickstart#23]
I'm trying on AWS and I got this error

~~~
Error: Error applying plan:
1 error(s) occurred:
* aws_security_group.rancher_sg_allowall: 1 error(s) occurred:
* aws_security_group.rancher_sg_allowall: Error revoking default egress rule for Security Group (sg-06351aed6c6e2d460): UnauthorizedOperation: You are not authorized to perform this operation.
~~~

I guess the policy for the user needs to be updated... Can you share the policy json for which this will work correctly?

**Comment by Emc1992** [comment]
Take a look at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policies-ec2-console.html#ex-security-groups and let me know if that helps

**Comment by bashofmann** [comment]
Closing in favour of https://github.com/rancher/quickstart/issues/163
