### ISSUE TITLE
UI  is  not accessible https://172.22.101.101

### ISSUE THREAD

**Issue by nutexan04** [rancher/quickstart#24]
I am not able to access the rancher UI at the URL. I can ping the ip address but I cannot connect to the UI.

**Comment by superseb** [comment]
What is running on the `server-01`? (`vagrant ssh server-01` and `docker ps -a`)

Can you reach it when you curl on `server-01`? Does the provisioning succeed?

**Comment by nutexan04** [comment]
Please close this request.

--

David
Sent from my phone.
On Apr 25, 2019, at 4:04 AM, Sebastiaan van Steenis <notifications@github.com<mailto:notifications@github.com>> wrote:

What is running on the server-01? (vagrant ssh server-01 and docker ps -a)

Can you reach it when you curl on server-01? Does the provisioning succeed?
