### ISSUE TITLE
terraform plan error - aws module

### ISSUE THREAD

**Issue by madhugoundla** [rancher/quickstart#32]
Hi, says cannot find the path specified.

Files - userdata_agent | userdata_server
 - main.tf
 - terraform.tfvars

![image](https://user-images.githubusercontent.com/49963882/56698814-d2503c00-66b8-11e9-8bcf-b298c1de41c8.png)

**Comment by superseb** [comment]
The files are there, you are probably running the `terraform` command outside of the `aws` folder. Can you try switching to the `aws` folder and then run the commands?

**Comment by superseb** [comment]
Let me know if you need help on this

**Comment by madhugoundla** [comment]
Hi, please close this, it worked. Sorry for the late reply.
