### ISSUE TITLE
vagrant quickstart eats too much CPU

### ISSUE THREAD

**Issue by supersexy** [rancher/quickstart#33]
I just wanted to quickly jump into Rancher but my first observation is a little bit worrying: the vagrant quickstart with 3 nodes eats way too much cpu for doing nothing. On the host the virtualbox machines are idling on about 25%, rancher gui shows me values from 35% to 54% for CPU - after a fresh installation, no payload on that cluster! 

On the same host an idling k3os vm will never go above 10%, mostly between 3% and 7%.

I know Virtualbox is not the target for production environments, but has this CPU burning to be expected? Looks more like a bug to me. 

Thanks for your attention!

**Comment by supersexy** [comment]
BTW what is the recommended way with rancher to gather more info in such situations? I was looking for some more metrics to identify the cpu intensive process but found nothing. Of course I can login to that host and look around, well, but that is not what I expected with a cluster manager. 
Do I have to setup metrics myself or did I miss something with installation? 
Thanks again!

**Comment by vincent99** [comment]
We've done a lot of work in k3os to reduce it, but this is just the way vanilla k8s is.  Monitoring  (prometheus/grafana, which you suggest you have on by looking at live CPU info in the UI) is also pretty resource intensive by itself.
