### ISSUE TITLE
Source for chrisurwin/RancherOS vagrant image

### ISSUE THREAD

**Issue by virtualstaticvoid** [rancher/quickstart#37]
Hello, 

I am unable to download the [`chrisurwin/RancherOS`](https://github.com/rancher/quickstart/blob/master/vagrant/Vagrantfile#L16) vagrant image used due to corporate policy restricting access to Vagrant Cloud for security reasons.

I've searched Google / GitHub, but haven't been able to track down the source code of the base image, so that I can built it myself. E.g. The base Vagrantfile or packer files etc.

Can anyone point me to the sources?

Thanks

**Comment by chrisurwin** [comment]
Hey,
I used the following repo to build the boxes before publishing them https://github.com/chriswayg/rancheros-box

**Comment by virtualstaticvoid** [comment]
Thanks!
