### ISSUE TITLE
AWS quickstart not working

### ISSUE THREAD

**Issue by slamkalukas** [rancher/quickstart#38]
Hello, i am trying to run Runcher terraform quickstart.
After preparing variables, we got an error:

Unspoorted block type
 on main.tf line 251, in data "template_file" "userdata_server":
 251: vars {
Blocks of type "vars" are not expected here. Did you mean to define argument "vars"? If so, use the equals sign to assign it a value.

Same for line 263

Terraform version: v0.12.0

Can you investigate please?
Thank you.

**Comment by ianwesterfield** [comment]
Same thing happens with the DO quickstart. I resolved this by adding `=` between `vars` and `{` on both lines per https://www.terraform.io/docs/providers/template/index.html

**Comment by ananth-racherla** [comment]
@ianwesterfield aws script was broken in a few additional places. See https://github.com/rancher/quickstart/pull/40

**Comment by b0nete** [comment]
> Same thing happens with the DO quickstart. Per https://www.terraform.io/docs/providers/template/index.html, I resolved these errors by inserting `=` between `vars` and `{` for each instance.

Thanks!, this work for me.
