### ISSUE TITLE
AWS gets stuck at Docker install

### ISSUE THREAD

**Issue by jtwebman** [rancher/quickstart#45]
The Terraform tool created everything but it never comes up. The system logs from the server ec2 instance are just this:
```
  130.444276] cloud-init[1445]: + export curlimage=appropriate/curl
[  130.447937] cloud-init[1445]: + curlimage=appropriate/curl
[  130.450622] cloud-init[1445]: + export jqimage=stedolan/jq
[  130.453002] cloud-init[1445]: + jqimage=stedolan/jq
[  130.456635] cloud-init[1445]: ++ command -v curl
[  130.458945] cloud-init[1445]: + '[' /usr/bin/curl ']'
[  130.464133] cloud-init[1445]: + curl -sL https://releases.rancher.com/install-docker/18.09.sh
[  130.469959] cloud-init[1445]: + sh
```
It stays there for a long time. I waited 15 minutes and it is still there. Will check in the morning when I get in.

**Comment by jtwebman** [comment]
Checked this morning and it is still stuck at the same place and nothing responds on the machine.

**Comment by superseb** [comment]
Can you confirm there is connectivity by running `curl -sL https://releases.rancher.com/install-docker/18.09.sh` on the host manually or `curl -vL https://releases.rancher.com/install-docker/18.09.sh`?

If that works, can you run the script using `bash -x` to trace where it gets stuck?

**Comment by jtwebman** [comment]
@superseb Ok found the issue it was using the default VPC which in our account has no access in or out. Switch to my test VPC and had no issue.
