### ISSUE TITLE
Support for AWS as cloud provider

### ISSUE THREAD

**Issue by codeNgamer** [rancher/quickstart#49]
I was wondering why the resulting cluster from aws isn't marked as using Amazon as cloud provider. A few questions I had for resolution.

1. Is this planned
2. do I just need to make changes to the script and add this functionality
3. do I extend `main.tf` to use `rancher2 provider` and mark resulting cluster from script as using Amazon as cloud provider

**Comment by superseb** [comment]
A quickstart is a way to quickly demonstrate functionality with the fewest dependencies needed. Using a node template/pool to reconcile/scale up nodes when they fail is not part of that. You can use the Terraform providers docs (https://www.terraform.io/docs/providers/rancher2/index.html) to help build this automatically.
