### ISSUE TITLE
* aws_security_group.rancher_sg_allowall: 1 error(s) occurred:

### ISSUE THREAD

**Issue by apaz037** [rancher/quickstart#5]
Hi!

Currently getting the following when using the quickstart to deploy to AWS.

* aws_security_group.rancher_sg_allowall: Error authorizing security group ingress rules: InvalidPermission.Malformed: Unsupported IP protocol "-1"  - supported: [tcp, udp, icmp]
	status code: 400, request id: GUID

**Comment by Oats87** [comment]
Hi!

Could you please let me know which AWS region you are working in?

**Comment by Oats87** [comment]
@apaz037 

Looking into this a bit further (https://github.com/terraform-providers/terraform-provider-aws/issues/1661), it appears that this error message may be caused due to a lack of a default-VPC. Do you have a default VPC on your AWS account?

**Comment by apaz037** [comment]
I am on us-west-1

I do not have a default VPC on my AWS account.  I'll see what I can do in that regard unless you know of a potential workaround!

Thank you so much for your help!  Really appreciate you taking the time to look into this.

**Comment by shaunc** [comment]
I'm getting this too. How do I use the Quickstart if I do not have a default VPC?

**Comment by Oats87** [comment]
This QuickStart is not compatible with AWS accounts without a default VPC.

**Comment by shaunc** [comment]
:( ... I'm a rancher newbie trying to get started. What is the easiest way to install without a default VPC, and what do I need to read to get started?

**Comment by shaunc** [comment]
Ah ... ok: creating default VPC isn't too hard -- and doesn't seem to conflict with my current setup. Ok -- ... never mind, and thanks for the quick reply!

**Comment by ivangrigolon** [comment]
I do have the same problem, although I have a default VPC already
