### ISSUE TITLE
aws provisioning failing reading the variables

### ISSUE THREAD

**Issue by hpjrvs** [rancher/quickstart#51]
HI, 
When I try to follow the quickstart tutorial with aws provisioning, the terraform variables and files are not read by the command"terraform init": 

```
➜  aws git:(master) ✗ terraform init                           
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing quickstart/aws/main.tf: At 3:16: Unknown token: 3:16 IDENT var.aws_access_key
```

If I replace the variables in the main.tf I'm able to get stuck in the next step, that is read the template file, follow the error: 

```
➜  aws git:(master) ✗ terraform init -var-file=terraform.tfvars
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing quickstart/aws/main.tf: At 124:20: Unknown token: 124:20 IDENT data.template_file.userdata_server.rendered
```

Not sure if is something related to my mac.

**Comment by bashofmann** [comment]
In case this is till relevant, the error message is because the used Terraform version is too old. The quickstarts need Terraform >=0.12.0.
This is also now mentioned in the README.

@nikkelma I think we can close this issue.
