### ISSUE TITLE
Vagrant quickstart kubernetes version cannot be empty

### ISSUE THREAD

**Issue by Oats87** [rancher/quickstart#53]
If the vagrant quickstart Kubernetes version is left empty, you end up with errors like: 
```
2020/01/14 03:37:17 [ERROR] getSvcOptions: error finding system image for  resource name may not be empty
2020/01/14 03:37:17 [ERROR] getK8sServiceOptions: k8sVersion  [resource name may not be empty]
```

This is solved by editing/saving the cluster (you don't have to change anything). Likely a change due to the KDM integration for 2.3+

**Comment by bashofmann** [comment]
Closing, since the vagrant config contains a default Kubernetes version now.
