### ISSUE TITLE
Provider "rke" not available for installation

### ISSUE THREAD

**Issue by sneakersgames** [rancher/quickstart#56]
```
Initializing provider plugins...
- Checking for available provider plugins...

Provider "rke" not available for installation.

A provider named "rke" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Error: no provider exists with the given name
```

Provider installed on both `~/ terraform.d/plugins/darwin_amd64` and `~/ terraform.d/plugins/darwin_amd64`, named both `terraform-provider-rke` and `terraform-provider-rke_v0.14.1`

![image](https://user-images.githubusercontent.com/473894/76699098-410bfe80-66aa-11ea-873e-0aa1f15c35a2.png)

**Comment by srirajan** [comment]
Got a similar error.

$ terraform12 init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "rke" not available for installation.

A provider named "rke" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Error: no provider exists with the given name

$ ls ~/.terraform.d/plugins/
darwin_amd64  terraform-provider-rke

$ ls ~/.terraform.d/plugins/darwin_amd64/
terraform-provider-rke

**Comment by outlawvikas** [comment]
> Provider "rke" not available for installation.
Please refer the terraform official documentation and try to use the "rancher2" as a provider
https://www.terraform.io/docs/providers/rancher2/index.html

**Comment by srirajan** [comment]
Thanks for the response. Rancher2 is already included in the providers and I am using the example described here https://github.com/rancher/quickstart/blob/master/rancher-common/provider.tf

However, after experimenting a bit, if I remove the RKE provider in the above template, it works

**Comment by nikkelma** [comment]
Hey all, this is a result of the RKE provider still being a community plugin and not able to be installed through `terraform init`. A [requirement in the README](https://github.com/rancher/quickstart/tree/3b25a4bd0030c6b895881a06af65280ba9c2e03e#requirements---cloud) gives a link to the installation process for the RKE provider. As soon as the RKE provider is an official plugin, the provider will be updated to allow `terraform init` to install all plugins.

**Comment by agreddyapps** [comment]
Matt - Will the "Terraform Provider for RKE" actively maintained to be compatible with current and future rke releases. I ask because I did not see this listed as on the official list of terraform providers on  https://www.terraform.io/docs/providers/ but found an obsolete link on https://github.com/rancher/terraform-provider-rke#using-the-provider pointing to https://www.terraform.io/docs/providers/rke/index.html

**Comment by shpwrck** [comment]
The rke provider is currently in the process of making it's way into https://www.terraform.io/docs/providers/, and will be maintained.

**Comment by nikkelma** [comment]
@sneakersgames I apologize for misunderstanding your original question - the issue according to your screenshot is that terraform expects platform-specific plugins to be installed under `<OS>_<arch>`. In the case of your screenshot, the expected folder name is `darwin_amd64` but it appears your folder is named `darwin-amd64` (notice the dash instead of an underscore).

**Comment by AlphaWong** [comment]
same issue. After I copy it.
```
/Users/Alpha/.terraform.d/plugins/darwin_amd64
total 127072
-rw-r--r--@ 1 Alpha  staff    62M Apr  7 16:04 terraform-provider-rke_darwin-amd64
```

**Comment by srirajan** [comment]
For me, doing the following helped. In rancher-common/provider.tf, comment the rke provider

# RKE provider - community plugin as of 2020-02-02
#provider "rke" {
#  version = "0.14.1"
#}

**Comment by AlphaWong** [comment]
> For me, doing the following helped. In rancher-common/provider.tf, comment the rke provider
> 
> ```
> # RKE provider - community plugin as of 2020-02-02
> #provider "rke" {
> #  version = "0.14.1"
> #}
> ```

true. but I do not know it will break something or not.

**Comment by AlphaWong** [comment]
I find out the reason. The current document is outdated.
u need to pick the `terraform-provider-rke` to project directory not ur `user directory`.
Also, u need to rename the `terraform-provider-rke` to `terraform-provider-rke_v.14.1_x4`
```
/Users/Alpha/works/src/github.com/quickstart/azure/.terraform/plugins/darwin_amd64
total 775832
-rwxr-xr-x  1 Alpha  staff   483B Apr  7 17:08 lock.json
-rwxr-xr-x  1 Alpha  staff   143M Apr  7 15:12 terraform-provider-azurerm_v2.0.0_x5
-rwxr-xr-x  1 Alpha  staff    53M Apr  7 15:12 terraform-provider-helm_v1.1.1_x4
-rwxr-xr-x  1 Alpha  staff    58M Apr  7 15:12 terraform-provider-kubernetes_v1.10.0_x4
-rwxr-xr-x  1 Alpha  staff    24M Apr  7 15:12 terraform-provider-local_v1.4.0_x4
-rwxr-xr-x  1 Alpha  staff    33M Apr  7 15:12 terraform-provider-rancher2_v1.8.2_x4
-rwxr-xr-x@ 1 Alpha  staff    62M Apr  7 16:04 terraform-provider-rke_v0.14.1_x4
```

**Comment by nikkelma** [comment]
#89 has been merged, are these documentation changes enough to close this issue?

**Comment by haimari** [comment]
> I find out the reason. The current document is outdated.
> 
> 1. rename it to `terraform-provider-rke_v0.14.1`
> 2. put it to `~/.terraform.d/plugins`
> 3. remove the `.terraform` in ur `project_directory`
> 4. run `terraform init`

Getting this error:

```
[aws] terraform init                                                                                                                                                                                     master  ✗
Initializing modules...
- rancher_common in ../rancher-common

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "helm" (hashicorp/helm) 1.0.0...
- Downloading plugin for provider "rancher2" (terraform-providers/rancher2) 1.8.3...

Provider "rke" not available for installation.

A provider named "rke" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

- Downloading plugin for provider "aws" (hashicorp/aws) 2.41.0...
- Downloading plugin for provider "tls" (hashicorp/tls) 2.1.1...
- Downloading plugin for provider "local" (hashicorp/local) 1.4.0...
- Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.10.0...

Error: no provider exists with the given name
```

**Comment by nikkelma** [comment]
@haimari Yes, this issue was created when the required version of the RKE provider was 0.14.1 - my comment above you references a PR that added [installation instructions for `terraform-provder-rke` in the README](https://github.com/rancher/quickstart#installing-terraform-provider-rke).

**Comment by matinats** [comment]
I was able to solve that issue by manually downloading the rke v1.1.5 as defined here: https://github.com/rancher/terraform-provider-rke and then creating a directory path ~/.terraform.d/plugins/registry.terraform.io/hashicorp/rke/1.1.5/linux_amd64/ and copying the unzipped file here as terraform-provider-rke.

**Comment by ahmad-sadia** [comment]
None of the above worked for me, had to paste terraform-provider-rke_v1.0.0 in .terraform/plugins in the project directory as shown in the screenshot bellow

![Screenshot 2022-04-06 at 00 41 52](https://user-images.githubusercontent.com/44840274/161862829-7d2542c2-f066-4422-b65f-8f0f662843cb.png)
