### ISSUE TITLE
vagrant behind corporate proxy

### ISSUE THREAD

**Issue by jhulick** [rancher/quickstart#6]
I'm unable to run rancher via vagrant behind a corporate proxy. I've installed the vagrant proxy plugin and configured that, but it seems rancher's docker isn't able to retrieve an image. 

What needs to be done to configure quickstart vagrant for corporate proxy? 

 Unable to find image 'rancher/rancher:latest' locally
    server-01: docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 52.206.40.44:443: getsockopt: connection refused.
    server-01: See 'docker run --help'.
    server-01: + true
    server-01: + wget -T 5 -c https://localhost/ping
    server-01: Connecting to localhost (127.0.0.1:443)
    server-01: wget: can't connect to remote host (127.0.0.1): Connection refused
    server-01: + sleep 5
    server-01: + true

**Comment by chrisurwin** [comment]
You would need to update the rancher_node and rancher_server scripts to add
`ros config set rancher.docker.environment "['http_proxy=http://<proxyip>:<proxyport>','https_proxy=http://proxyip>:<proxyport>','HTTP_PROXY=http://$cache_ip:3128','HTTPS_PROXY=http://proxyip>:<proxyport>','no_proxy=server.rancher.vagrant,localhost,127.0.0.1','NO_PROXY=server.rancher.vagrant,localhost,127.0.0.1']"` setting your proxy values, and then run 
`system-docker restart docker`
`sleep 5`
These would need to be placed early in the script.

**Comment by gbonnefille** [comment]
It seems that the `ros` command itself needs the proxy settings, in order to update the engine version.

Setting the http_proxy and https_proxy variables directly on the script shell solve this step.

What about setting the proxy in the `/etc/environment` from the vagrant script in order to have these settings available for any command?
