### ISSUE TITLE
[AWS] Configure the provider credentials with a profile

### ISSUE THREAD

**Issue by dkeightley** [rancher/quickstart#60]
The default `~/.aws/credentials` file is often configured to store credentials (access/secret keys) for AWS CLI and SDK use. With that, to simplify the aws quickstart, these can be leveraged in the provider opposed to configuring these manually in a .tfvars file. 
  * https://www.terraform.io/docs/providers/aws/index.html#shared-credentials-file

Example:

```hcl
 provider "aws" {
  region = var.aws_region
}
```

**Comment by nikkelma** [comment]
Thanks for this - I like the idea and the simplicity of the terraform code.

Docs would need to be updated to reflect the additional dependency on the AWS CLI, or we'd need to implement a "smart" provider that falls back to variables if the profile doesn't exist, or we'd need to include instructions on how to use the quickstart without the AWS CLI installed by commenting out the applicable provider sections.

Curious how many quickstart users have the AWS CLI installed... if many do, then this makes lots of sense; if few do, then I'd avoid it for consistency and simplicity.

Wouldn't mind getting @chrisurwin's thoughts on this.

**Comment by chrisurwin** [comment]
We try to keep the quickstarts as self contained as possible, people can take these as a building block and enhance them as they see fit. This isn't something I want to add at this time.
