### ISSUE TITLE
Why not use RancherOS on DigitalOcean instead of Ubuntu 16.04?

### ISSUE THREAD

**Issue by nikolay** [rancher/quickstart#8]

**Comment by superseb** [comment]
RancherOS had a bug using shell scripts in cloud-init/config so we couldn't easily use or present it as an option. Also there is a resource increase in v1.4 which will be fixed in v1.5. So we will consider switching to RancherOS by default when v1.5 is released.

**Comment by alfonmga** [comment]
v1.5.1 is here. Could RancherOS be used now?

**Comment by antoniomo** [comment]
https://github.com/rancher/os/issues/2367

**Comment by chrisurwin** [comment]
People are free to change/enhance any aspects of the quickstart, having ubuntu as a base means that people are more comfortable as it's not introducing another new thing that they then can't troubleshoot without help.
